apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payflow.fullname" . }}-config
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: "kubernetes,{{ .Values.global.environment }}"
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  USER_SERVICE_URI: "http://{{ include "payflow.fullname" . }}-user-service:8081"
  WALLET_SERVICE_URI: "http://{{ include "payflow.fullname" . }}-wallet-service:8082"
  PAYMENT_SERVICE_URI: "http://{{ include "payflow.fullname" . }}-payment-service:8083"
  LEDGER_SERVICE_URI: "http://{{ include "payflow.fullname" . }}-ledger-service:8084"
  MERCHANT_SERVICE_URI: "http://{{ include "payflow.fullname" . }}-merchant-service:8085"
  FRAUD_SERVICE_URI: "http://{{ include "payflow.fullname" . }}-fraud-service:8086"
  NOTIFICATION_SERVICE_URI: "http://{{ include "payflow.fullname" . }}-notification-service:8087"
