server:
  port: 8086

spring:
  application:
    name: fraud-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${FRAUD_DB_NAME:fraud_db}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:postgres}}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:~}
      ssl:
        enabled: ${REDIS_SSL:false}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: fraud-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

payflow:
  jwt:
    secret: ${JWT_SECRET:payflowSuperSecretProductionKeyMustBeAtLeast256BitsLongForHmacSha256!}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
