apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payflow

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - core-services.yaml
  - supporting-services.yaml
  - hpa-and-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: payflow-platform
  app.kubernetes.io/managed-by: kustomize
