apiVersion: v1
kind: Secret
metadata:
  name: payflow-common-secrets
  namespace: payflow
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres_payflow_secure_2026"
  REDIS_PASSWORD: "redis_payflow_secure_2026"
  JWT_SECRET: "payflowSuperSecretProductionKeyMustBeAtLeast256BitsLongForHmacSha256!"
  GRAFANA_PASSWORD: "payflow_grafana_admin_2026"
